name: http_client_hoc081098_example
description: http_client_hoc081098_example
publish_to: none
version: 1.0.0-dev.0

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  http_client_hoc081098:
  cancellation_token_hoc081098: ^2.0.0

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  http_client_hoc081098:
    path: ../../http_client_hoc081098