name: http_client_hoc081098
description: Simple and powerful HTTP client for Flutter and Dart application.
version: 1.0.0-dev.0
homepage: https://github.com/hoc081098/http_client_hoc081098.git
repository: https://github.com/hoc081098/http_client_hoc081098.git
issue_tracker: https://github.com/hoc081098/http_client_hoc081098/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  meta: ^1.7.0
  rxdart_ext: ^0.2.5
  cancellation_token_hoc081098: ^1.0.0-beta.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
