name: http_client_hoc081098
description: Simple and powerful HTTP client for Flutter and Dart application.
version: 0.0.1-dev.0
homepage: https://github.com/hoc081098/http_client_hoc081098.git
repository: https://github.com/hoc081098/http_client_hoc081098.git
issue_tracker: https://github.com/hoc081098/http_client_hoc081098/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  meta: ^1.7.0
  rxdart_ext: ^0.3.0
  cancellation_token_hoc081098: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.17.15
  mockito: ^5.4.2
  build_runner: ^2.4.9
  collection: ^1.18.0

#  dart run build_runner build --delete-conflicting-outputs